name: Mind your language

on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited
  pull_request_review_comment:
    types:
      - created
      - edited

permissions:
    issues: write
    pull-requests: write

concurrency:
    group: "language-check"
    cancel-in-progress: false

jobs:
  echo_issue_comment:
    runs-on: ubuntu-latest
    name: profanity check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Profanity check step
        uses: tailaiw/mind-your-language-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}